apiVersion: v1
kind: Pod
metadata:
  name: my-second-app
  labels:
    app: nginx
spec:
  containers:
  - name: my-second-app
    image: kubedevio/nginx-color:blue
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
