apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  selector:
    app: my-first-app
  type: NodePort
  ports:
  - port: 8080
    #30000 a 32677
    nodePort: 30000
    #targetPort: <Target Port>
